name: Build Windows DLL

on:
  push:
    branches:
      - main
      - feature/*
      - bugfix/*
    tags:
      - "v*"
  pull_request:
    branches:
      - main
  workflow_dispatch:

permissions:
  contents: write

env:
  ZLIB_COMMIT: 09155eaa2f9270dc4ed1fa13e2b4b2613e6e4851
  ZSTD_COMMIT: 794ea1b0afca0f020f4e57b6732332231fb23c70
  BROTLI_COMMIT: ed738e842d2fbdf2d6459e39267a633c4a9b2f5d
  BORINGSSL_COMMIT: 673e61fc215b178a90c0e67858bbf162c8158993
  CURL_TAG: curl-8_15_0
  NGHTTP2_COMMIT: 8f44147c385fb1ed93a6f39911eeb30279bfd2dd
  NGHTTP3_TAG: v1.15.0
  NGTCP2_TAG: v1.20.0

jobs:
  build-windows:
    name: Build Windows x86_64 DLL
    runs-on: windows-latest
    steps:
      - name: Configure Pagefile
        uses: al-cheb/configure-pagefile-action@v1.3
        with:
          minimum-size: 16GB
          maximum-size: 16GB
          disk-root: "C:"

      - name: Install Python 3.11
        uses: actions/setup-python@v5
        with:
          python-version: "3.11"

      - name: Check out the repo
        uses: actions/checkout@v4

      - name: Install NASM
        shell: cmd
        run: choco install nasm -y

      - name: Fetch and patch deps
        shell: bash
        run: ./win/deps.sh

      - name: Build
        shell: cmd
        run: ./win/build.bat vcvars64
        env:
          DISABLE_ASM_ARM64: "false"

      - name: Build tarball
        shell: bash
        run: |
          if [[ "${{ startsWith(github.ref, 'refs/tags/') }}" == "true" ]]; then
            tar czf libcurl-impersonate-${{ github.ref_name }}.x86_64-win32.tar.gz -C ./packages .
          else
            tar czf libcurl-impersonate.x86_64-win32.tar.gz -C ./packages .
          fi

      - name: Upload artifacts
        uses: actions/upload-artifact@v4
        with:
          name: libcurl-impersonate.x86_64-win32
          path: ./libcurl-impersonate*.tar.gz

      - name: Upload release file
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/')
        with:
          files: libcurl-impersonate-${{ github.ref_name }}.x86_64-win32.tar.gz
